apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pod-logs-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: scanner-sa
  namespace: default
roleRef:
  kind: Role
  name: read-pod-logs-role
  apiGroup: rbac.authorization.k8s.io
