apiVersion: v1
kind: PersistentVolume
metadata:
  name: scan-results-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /app/scan-results

