apiVersion: v1
kind: ServiceAccount
metadata:
  name: scanner-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-scanner-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "deployments"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-scanner-rolebinding
subjects:
- kind: ServiceAccount
  name: scanner-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-scanner-role
  apiGroup: rbac.authorization.k8s.io
