apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-list-role-binding
subjects:
- kind: ServiceAccount
  name: scanner-sa
  namespace: sec
roleRef:
  kind: Role
  name: job-list-role
  apiGroup: rbac.authorization.k8s.io
