apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: scan-results-pvc
  namespace: sec

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
